// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGNA.Models;

#nullable disable

namespace SIGNA.Migrations
{
    [DbContext(typeof(PessoaContext))]
    [Migration("20221005194857_DBMigration")]
    partial class DBMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SIGNA.Models.DataModel", b =>
                {
                    b.Property<int>("PESSOA_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CNPJ_CPF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NOME_FANTASIA")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PESSOA_ID");

                    b.ToTable("PESSOA");

                    b.HasData(
                        new
                        {
                            PESSOA_ID = 1,
                            CNPJ_CPF = "694.678.770-66",
                            NOME_FANTASIA = "Coca Coallers"
                        },
                        new
                        {
                            PESSOA_ID = 2,
                            CNPJ_CPF = "265.752.130-49",
                            NOME_FANTASIA = "Nika"
                        },
                        new
                        {
                            PESSOA_ID = 3,
                            CNPJ_CPF = "102.584.620-60",
                            NOME_FANTASIA = "DJDonalds"
                        },
                        new
                        {
                            PESSOA_ID = 4,
                            CNPJ_CPF = "984.814.520-68",
                            NOME_FANTASIA = "Soda King"
                        },
                        new
                        {
                            PESSOA_ID = 5,
                            CNPJ_CPF = "563.968.300-78",
                            NOME_FANTASIA = "Pólen Station"
                        },
                        new
                        {
                            PESSOA_ID = 6,
                            CNPJ_CPF = "720.070.510-10",
                            NOME_FANTASIA = "Beto Carreto"
                        },
                        new
                        {
                            PESSOA_ID = 7,
                            CNPJ_CPF = "834.227.360-18",
                            NOME_FANTASIA = "Mercadão"
                        },
                        new
                        {
                            PESSOA_ID = 8,
                            CNPJ_CPF = "425.927.670-02",
                            NOME_FANTASIA = "Suprema"
                        },
                        new
                        {
                            PESSOA_ID = 9,
                            CNPJ_CPF = "878.451.000-56",
                            NOME_FANTASIA = "Grapes"
                        },
                        new
                        {
                            PESSOA_ID = 10,
                            CNPJ_CPF = "467.754.590-17",
                            NOME_FANTASIA = "Soni Edison"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
